SELECT *
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'EMP';

SELECT *
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'DEPT';

SELECT *
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'SALGRADE';

SELECT DISTINCT JOB, DEPTNO
FROM EMP;

SELECT ALL JOB, DEPTNO
FROM EMP;

SELECT ENAME, SAL, SAL * 12 + COMM AS ANNSAL, COMM
FROM EMP;

SELECT *
FROM EMP
ORDER BY DEPTNO, SAL DESC;

SELECT *
FROM EMP
WHERE JOB NOT IN ('MANAGER', 'SALESMAN');

SELECT *
FROM EMP
WHERE ENAME LIKE 'S%';

SELECT *
FROM EMP
WHERE ENAME LIKE '__L%';

SELECT *
FROM EMP
WHERE ENAME LIKE '%AM%';

SELECT *
FROM EMP
WHERE COMM IS NULL;

-- UNION -> 결합 연산자, 중복제거
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- UNION ALL -> 결합 연산자, 중복포함
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- MINUS -> 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- INTERSECT -> 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

