-- cross join, 카테시안 곱, 교차 조인
SELECT *
FROM EMP,
     DEPT
ORDER BY EMPNO;


SELECT *
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO -- 해당사항 맞는 row만 남기기 위해서
ORDER BY EMPNO;

-- 테이블 별칭
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

-- 내부조인: INNER JOIN 기준열의 데이터가 유효한 경우만 표시
SELECT E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND SAL >= 3000
ORDER BY EMPNO;

-- 비등가 조인: 하나의 값이 대응되지 않는 경우의 조인
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E,
     SALGRADE S
WHERE E.SAL BETWEEN LOSAL AND HISAL
ORDER BY SAL DESC;

-- 자체조인: 한 테이블 내에서 참조가 있을경우 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
FROM EMP E1,
     EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 외부조인: OUTER JOIN 기준열의 한쪽이 NULL이어도 강제로 출력하는 방식

-- 왼쪽 외부 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
FROM EMP E1,
     EMP E2
WHERE E1.MGR = E2.EMPNO(+)
ORDER BY E1.EMPNO;

-- 오른쪽 외부 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
FROM EMP E1,
     EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;

-- NATURAL JOIN
SELECT E.EMPNO,
       E.ENAME,
       E.JOB,
       E.MGR,
       E.HIREDATE,
       E.SAL,
       E.COMM,
       DEPTNO,
       D.DNAME,
       D.LOC
FROM EMP E
         NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;

-- JOIN ~ USING
SELECT E.EMPNO,
       E.ENAME,
       E.JOB,
       E.MGR,
       E.HIREDATE,
       E.SAL,
       E.COMM,
       DEPTNO,
       D.DNAME,
       D.LOC
FROM EMP E
         JOIN DEPT D USING (DEPTNO)
ORDER BY DEPTNO, E.EMPNO;

-- JOIN ON
SELECT E.EMPNO,
       E.ENAME,
       E.JOB,
       E.MGR,
       E.HIREDATE,
       E.SAL,
       E.COMM,
       E.DEPTNO,
       D.DNAME,
       D.LOC
FROM EMP E
         JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE SAL <= 3000
ORDER BY DEPTNO, E.EMPNO;

-- LEFT OUTER JOIN
SELECT E1.EMPNO,
       E1.ENAME,
       E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1
         LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- RIGHT OUTER JOIN
SELECT E1.EMPNO,
       E1.ENAME,
       E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1
         RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- FULL OUTER JOIN
SELECT E1.EMPNO,
       E1.ENAME,
       E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1
         FULL OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- practice
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E
         JOIN
     DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.SAL > 2000
ORDER BY D.DEPTNO, E.EMPNO;

SELECT D.DEPTNO,
       D.DNAME,
       TRUNC(AVG(SAL)) AS AVG_SAL,
       MAX(SAL)        AS MAX_SAL,
       MIN(SAL)        AS MIN_SAL,
       COUNT(*)        AS CNT
FROM EMP E
         JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
GROUP BY D.DEPTNO, D.DNAME
ORDER BY D.DEPTNO;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E
         JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY D.DEPTNO, E.ENAME;

SELECT D.DEPTNO,
       D.DNAME,
       E1.EMPNO,
       E1.ENAME,
       E1.MGR,
       E1.SAL,
       SG.LOSAL,
       SG.HISAL,
       SG.GRADE,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1
         JOIN SALGRADE SG ON (E1.SAL BETWEEN SG.LOSAL AND SG.HISAL)
         RIGHT OUTER JOIN DEPT D ON (E1.DEPTNO = D.DEPTNO)
         LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.DEPTNO, E1.EMPNO;
