/*
    Sub Query

    - 특수한 몇몇 경우를 제외한 대부분의 서브쿼리에서는 ORDER BY 절을 사용할 수 없다.
    - 메인쿼리의 비교 대상 데이터가 하나라면 서브쿼리의 SELECT절도 같은 자료형인 열을 하나만 지정해야함.
    - 메인쿼리의 연산 행수와 서브쿼리 결과의 행수가 일치해야한다.
    */


SELECT *
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'JONES');

/*
    다중행 서브쿼리
    - IN, ANY, SOME, ALL, EXISTS
*/

SELECT *
FROM EMP
WHERE DEPTNO IN (20, 30);

SELECT *
FROM EMP
WHERE SAL IN (SELECT MAX(SAL)
              FROM EMP
              GROUP BY DEPTNO);



SELECT *
FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL)
                 FROM EMP
                 GROUP BY DEPTNO);

SELECT *
FROM EMP
WHERE SAL = SOME (SELECT MAX(SAL)
                  FROM EMP
                  GROUP BY DEPTNO);

SELECT *
FROM EMP
WHERE SAL < ANY (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30)
ORDER BY SAL, EMPNO;

SELECT *
FROM EMP
WHERE DEPTNO = 30;

-- 부서번호가 30번인 사원의 최소 급여보다 많이 받는 사원
SELECT *
FROM EMP
WHERE SAL > ANY (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30);

-- 부서번호가 30번인 사원의 최소급여보다 더 적은 급여를 받는 사원
SELECT *
FROM EMP
WHERE SAL < ALL (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30);

-- 부서 번호가 30번인 사원의 최대 급여보다 더 많은 급여를 받는 사원
SELECT *
FROM EMP
WHERE SAL > ALL (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30);

-- EXISTS
SELECT *
FROM EMP
WHERE EXISTS(SELECT DNAME
             FROM DEPT
             WHERE DEPTNO = 50);

/*
    다중열 쿼리
    - 서브쿼리 -> 부서번호별로 최대 급여 받는사람 리스트 출력
    - 메인쿼리 -> 부서번호가 같고, 급여가 최대급여인 사원
    - 최종 -> 각 부서별 최대급여를 받고있는 사원
*/
SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                        FROM EMP
                        GROUP BY DEPTNO);

SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

-- 인라인 뷰: FROM 절에 사용되는 서브쿼리
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
     (SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO;

-- WITH절 사용하는 방식
WITH E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
     D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM E10,
     D
WHERE E10.DEPTNO = D.DEPTNO;

-- Scalar Subquery: SELECT절에서 사용하는 서브쿼리
SELECT EMPNO,
       ENAME,
       JOB,
       SAL,
       (SELECT GRADE
        FROM SALGRADE
        WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE, -- 반드시 하나의 결과만 반환해야함.
       DEPTNO,
       (SELECT DNAME
        FROM DEPT
        WHERE E.DEPTNO = DEPT.DEPTNO)        AS DNAME     -- 반드시 하나의 결과만 반환해야함.
FROM EMP E;

-- practice
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.JOB = (SELECT JOB
               FROM EMP
               WHERE EMP.ENAME = 'ALLEN');

SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, SG.GRADE
FROM EMP E,
     DEPT D,
     SALGRADE SG
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL BETWEEN SG.LOSAL AND SG.HISAL
  AND E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO;

WITH E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
     D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.JOB, E10.DEPTNO, D.DNAME, D.LOC
FROM E10,
     D
WHERE E10.DEPTNO = D.DEPTNO
  AND E10.JOB NOT IN (SELECT DISTINCT E30.JOB FROM EMP E30 WHERE E30.DEPTNO = 30);

SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E,
     DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.DEPTNO = 10
  AND E.JOB NOT IN (SELECT DISTINCT E30.JOB FROM EMP E30 WHERE E30.DEPTNO = 30);

SELECT E.EMPNO, E.ENAME, E.SAL, SG.GRADE
FROM EMP E,
     SALGRADE SG
WHERE E.SAL BETWEEN SG.LOSAL AND SG.HISAL
  AND E.SAL > (SELECT MAX(SAL)
               FROM EMP
               WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, SG.GRADE
FROM EMP E,
     SALGRADE SG
WHERE E.SAL BETWEEN SG.LOSAL AND SG.HISAL
  AND E.SAL > ALL (SELECT SAL
                   FROM EMP
                   WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;
