-- 기존 테이블을 복사해서 복제 테이블 생성
CREATE TABLE DEPT_TEMP
AS
SELECT *
FROM DEPT;

SELECT *
FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

INSERT INTO DEPT_TEMP
VALUES (60, 'NETWORK', 'BUSAN');

-- data를 복사하지 않고 복제 테이블 생성
CREATE TABLE EMP_TEMP
AS
SELECT *
FROM EMP
WHERE 1 <> 1;

SELECT *
FROM EMP_TEMP;

-- 날짜 데이터 입력
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (3111, 'gildong', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);


-- 서브쿼리를 사용하여 한번에 데이터 입력하기, MERGE문 사용가능
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
-- VALUES 절을 사용하지 않음에 유의
SELECT E.EMPNO, -- 추가할 데이터 열과 검색되는 데이터 열의 개수와 타입을 일치시키기
       E.ENAME,
       E.JOB,
       E.MGR,
       E.HIREDATE,
       E.SAL,
       E.COMM,
       E.DEPTNO
FROM EMP E,
     SALGRADE SG
WHERE E.SAL BETWEEN SG.LOSAL AND SG.HISAL
  AND SG.GRADE = 1;

SELECT *
FROM EMP_TEMP;

CREATE TABLE DEPT_TEMP2
AS
SELECT *
FROM DEPT;

SELECT *
FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';

ROLLBACK;

SELECT table_name, degree
FROM user_tables
WHERE table_name = 'DEPT_TEMP2';


ALTER SESSION DISABLE PARALLEL DML;

-- 데이터 일부만 수정
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE',
    LOC   = 'SEOUL'
WHERE DEPTNO = 40;

SELECT *
FROM DEPT_TEMP2;

-- 서브쿼리를 이용하여 수정
UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC
                    FROM DEPT
                    WHERE DEPTNO = 40)
WHERE DEPTNO = 40;


CREATE TABLE EMP_TEMP2 AS
SELECT *
FROM EMP;

SELECT *
FROM EMP_TEMP2;

SELECT *
FROM EMP;

-- 서브쿼리를 사용해서 데이터 삭제하기
DELETE
FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
                FROM EMP_TEMP2 E,
                     SALGRADE SG
                WHERE E.SAL BETWEEN SG.LOSAL AND SG.HISAL
                  AND SG.GRADE = 3
                  AND DEPTNO = 30);

-- practice
CREATE TABLE HW_EMP AS
SELECT *
FROM EMP;
CREATE TABLE HW_DEPT AS
SELECT *
FROM DEPT;
CREATE TABLE HW_SALGRADE AS
SELECT *
FROM SALGRADE;

SELECT *
FROM HW_EMP;
SELECT *
FROM HW_DEPT;
SELECT *
FROM HW_SALGRADE;

INSERT INTO HW_DEPT
VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO HW_DEPT
VALUES (60, 'SQL', 'ILSAN');
INSERT INTO HW_DEPT
VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO HW_DEPT
VALUES (80, 'DML', 'BUNDANG');

UPDATE HW_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
             FROM HW_EMP);

SELECT COUNT(*)
FROM EMP
WHERE SAL > 2073;

SELECT AVG(SAL)
FROM HW_EMP;

